In [30]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [31]:
data = pd.read_csv("./mushrooms.csv")
data

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [32]:
le = LabelEncoder()
le.fit(data["cap-shape"])
np.unique(data["cap-shape"])

array(['b', 'c', 'f', 'k', 's', 'x'], dtype=object)

In [33]:
le2 = LabelEncoder()
le2.fit_transform(data["class"])

array([1, 0, 0, ..., 0, 1, 0])

In [34]:
data["cap-shape"] = en
data["class"] = le.fit_transform(data["class"])
data.head()

class  cap-shape cap-surface cap-color bruises odor gill-attachment  \
0      1          5           s         n       t    p               f   
1      0          5           s         y       t    a               f   
2      0          0           s         w       t    l               f   
3      1          5           y         w       t    p               f   
4      0          5           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [35]:
X = np.array(data.iloc[:,1:])
y = np.array(data.iloc[:,0])
print(X,y)

[[5 's' 'n' ... 'k' 's' 'u']
 [5 's' 'y' ... 'n' 'n' 'g']
 [0 's' 'w' ... 'n' 'n' 'm']
 ...
 [2 's' 'n' ... 'b' 'c' 'l']
 [3 'y' 'n' ... 'w' 'v' 'l']
 [5 's' 'n' ... 'o' 'c' 'l']] [1 0 0 ... 0 1 0]


In [36]:
#total classes are 2
np.unique(y)

array([0, 1])

### Splitting the data into trian and test data

In [37]:
from sklearn.model_selection import train_test_split


In [38]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [39]:
X_train

array([[0, 's', 'w', ..., 'w', 'n', 'g'],
       [3, 's', 'e', ..., 'w', 'c', 'w'],
       [0, 'f', 'w', ..., 'w', 'n', 'g'],
       ...,
       [5, 'f', 'p', ..., 'k', 'v', 'd'],
       [2, 'y', 'g', ..., 'h', 'y', 'g'],
       [2, 'f', 'e', ..., 'n', 'y', 'd']], dtype=object)

In [40]:
y_train

array([0, 0, 0, ..., 1, 1, 0])

### Implementation of Naive bayes

In [41]:
def prior_pb(y_train,label):
    num = np.sum(y_train==label)
    den = y_train.shape[0]
    return num/den


def cond_pb(X_train,y_train,f,clas,label):
    filtered = X_train[y_train==label]
    num = np.sum(filtered[:,f]==clas)
    den = np.sum(y_train==label)
    return num/den
prior_pb(y_train,1)

0.4789967687336513

In [ ]:
def predict(x_train,y_train,xtest):
    """Xtest is a single testing point, n features"""
    
    classes = np.unique(y_train)
    pred = []
    n_features = x_train.shape[1]
    post_probs = [] # List of prob for all classes and given a single testing point
    #Compute Posterior for each class
    for label in classes:

            #Post_c = likelihood*prior
            likelihood = 1.0
            for f in range(n_features):
                cond = cond_pb(x_train,y_train,f,xtest[f],label)
                likelihood *= cond

            prior = prior_pb(y_train,label)
            post = likelihood*prior
            post_probs.append(post)
    pred = np.argmax(post_probs)
    return pred
def Naive(X_train,y_train,X_test):
    pred = [] 
    for i in range(len(X_test)):
        pred.append(predict(X_train,y_train,X_test[i]))
    return pred
y_pred = Naive(X_train,y_train,X_test)

In [ ]:
def score(y,y_pred): 
    num = np.sum((y_test - y_pred)**2)
    den = np.sum((y_test-np.mean(y_test)**2))
    return 1 - num/den
score(y_test,y_pred) *100

In [ ]:
y_test